### ISSUE TITLE
Adding new documents

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#181]
When adding a new document (pdf) the preview function doesn't function right. 

In the admin:
When making a item in the category 'document' and you add a pdf as media item, you don't see the document (only the title). When viewing older documents you do see the 'preview'
For example
old: https://www.filmfonds.nl/en/admin/edit/2222
Screenshot: [old_document](https://cloud.githubusercontent.com/assets/19573451/18472619/cf5e8d34-79b8-11e6-9b4e-d4ae9125e679.png)

new: https://www.filmfonds.nl/nl/admin/edit/3884
Screenshot: [Uploading New_document.png…]()

In the front-end:
In the front-end the preview of the document also isn't shown for new documents, where it does for older ones. 
For example: https://www.filmfonds.nl/nl/page/2874/vacatures
Old:
Screenshot: [old_document_fe](https://cloud.githubusercontent.com/assets/19573451/18472693/37156e3e-79b9-11e6-9e1d-f8d325a23bbd.png)

New: 
Screenshot: [new_document_fe](https://cloud.githubusercontent.com/assets/19573451/18472702/45b4a806-79b9-11e6-8623-756990352529.png)

I found this problem only on production, not on test and acceptatie servers.

**Comment by ddeboer** [comment]
> I found this problem only on production, not on test and acceptatie servers.

Let’s hope it’s fixed in the new release, then.

**Comment by ddeboer** [comment]
ginger01 has been upgraded to Ginger 0.15.0. Has this issue been fixed there?

**Comment by loetie** [comment]
Seems not to be fixed. Still a problem on ginger01 (naturalis). No preview on the edit page.

**Comment by kathleenvw** [comment]
This is no longer a problem, so i'm closing the issue.
